### ISSUE TITLE
futil not found in scipy v 0.17

### ISSUE THREAD

**Issue by qwrrty** [valentin012/conspeech#10]
After installing scipy, scikit-learn and nltk, `python demo.py` turns up this:

```
(py)pierce-osx:conspeech pierce$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import con_util
  File "/Users/pierce/conspeech/con_util.py", line 6, in <module>
    from scipy.stats import futil
ImportError: cannot import name futil
```

I am not very familiar with scipy, but from browsing the source on github, it looks as if scipy.stats.futil was dropped between scipy 0.16 and 0.17.

**Comment by tintamarre** [comment]
Same here ... I used `pip2 install scipy==0.16.0`
