### ISSUE TITLE
OSError in Mac OS X 10.11

### ISSUE THREAD

**Issue by fauria** [valentin012/conspeech#4]
Running:

```
git clone https://github.com/valentin012/conspeech.git
cd conspeech
sudo pip install nltk sklearn
python demo.py RY 0.25
```

Throws:

```
[constructing dataset...]
Traceback (most recent call last):
  File "demo.py", line 37, in <module>
    (dataset,vocab) = construct_dataset([TRAIN_DIR,TEST_DIR,DEV_DIR])
  File "/Users/fauria/github/conspeech/con_util.py", line 48, in construct_dataset
    for f in sorted(os.listdir(p)): 
OSError: [Errno 2] No such file or directory: 'convote_v1.1\\data_stage_three/training_set'
```

Some files seems to be missing:

```
ls -R convote_v1.1/
readme.txt
```

**Comment by jtbarker** [comment]
Same issue here:

OSError: [Errno 2] No such file or directory: 'convote_v1.1\data_stage_three/training_set'

**Comment by karthikjoshi** [comment]
OSError: [Errno 2] No such file or directory: 'convote_v1.1\data_stage_three/training_set'
My mac version is 10.9.2

**Comment by qguv** [comment]
PR #5 solves this problem. You can try using [the PR author's fork](https://github.com/josefdlange/conspeech) or applying [the patch](https://github.com/josefdlange/conspeech/commit/a1146a863341b75c3dc97f938e289c5881851128.patch) yourself if you're into that sort of thing.

**Comment by wankbank** [comment]
In OSX you can also fix this by inserting the following in `con_util.py` just above the line with the error:

```
        if os.name is 'posix': p = p.replace('\\','/')
```

https://gist.github.com/wankbank/e81fe248e0aa728cf271#file-con_util-py-L48
